config/routes.rb
Rails.application.routes.draw do
  root "bands#index"
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :string           not null
#  album_type :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  ALBUM_TYPES = %w(live studio)

  validates :band_id, :name, :album_type, presence: true
  validates :name, uniqueness: true
  validates :album_type, inclusion: { in: ALBUM_TYPES }

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  name       :string           not null
#  track_type :string           not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  TRACK_TYPES = %w(regular bonus)
  validates :album_id, uniqueness: {scope: :name}
  validates :album_id, :name, :track_type, presence: true
  validates :track_type, inclusion: { in: TRACK_TYPES }
  
  belongs_to :album
  has_one :band, through: :album, source: :band
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return nil unless @user
    @user if @user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index

  end

  def new
    @album = Album.new

    @band = Band.find_by_id(params[:band_id])
    
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url @album
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def show
    @album = Album.find(params[:id])

    render :show
  end

  def update
  end

  def destroy
  end

  def album_params
    params.require(:album).permit(:band_id, :name, :album_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logged_in?
    current_user != nil
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      flash.notice = "#{@band.name} successfully added"
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def show
    @band = Band.find(params[:id])

    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      flash.notice = "Updated band"
      redirect_to band_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end

  end

  def destroy
    @band = Band.find(params[:id])
    if @band.nil?
      flash[:error] = "Could not find band with id: #{params[:id]}"
    else
      flash.notice = "Successfuly deleted #{@band.name}"
      @band.destroy
    end

    redirect_to root_url
  end

  def band_params
    params.require(:band).permit(:name)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to bands_url
    else
      @user = User.new
      render :new
    end
  end

  def create
    user = User.new(user_params)

    @user = User.find_by_credentials(user.email, user.password)

    if @user.nil?
      flash.now[:error] = "Invalid credentials try again"
      @user = User.new(email: user.email)
      render :new
    else
      login!(@user)
      redirect_to @user
    end
  end

  def destroy
    logout!

    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index

  end

  def new
    @album = Album.find_by_id(params[:album_id])
    @track = Track.new
  end

  def create

    @track = Track.new(track_params)
    @album = @track.album
    if @track.save
      flash.notice = "#{@track.name} successfully added to #{@track.album.name}"
      redirect_to album_url(@track.album)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def show
    @band = Band.find(params[:id])

    render :show
  end

  def update
  end

  def destroy
  end

  def track_params
    params.require(:track).permit(:name, :album_id, :track_type, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to bands_url
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

    render :show
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_input
    html = <<-HTML
      <input name ="authenticity_token"
        type="hidden"
        value="<%=  form_authenticity_token %>">
      HTML

    html.html_safe
end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>Add an album</h1>
<form action="<%= albums_url %>" method="post">
  <%= auth_input %>

  <label for="album_name">Name</label>
  <input type="text"
   name="album[name]"
   id='album_name'
   value="<%= @album.name %>"><br>

  <label for="album_band_id">Band</label>
  <select name="album[band_id]" id="album_band_id">
    <% Band.all.each do |band| %>
      <option
        <%= params[:band_id].to_i == band.id ? "selected" : ""%>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select><br>

  <% Album::ALBUM_TYPES.each do |album_type| %>
  <label for="album_type_<%= album_type %>">
    <%= "#{ album_type }" %>
  </label>
  <input type="radio"
    name="album[album_type]"
    id="album_type_<%= album_type %>"
    value="<%= album_type %>"
    <%= 'checked="checked"' if @album.album_type == album_type %>>
  <% end %><br>

  <input type="submit" value="submit">
</form>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<ol>
  <% @album.tracks.order('id').each do |track| %>
  <li>
    <%= link_to "#{track.name}", track_url(track) %>
  </li>
  <% end %>
</ol>
<%= link_to "#{@album.band.name}", band_url(@album.band) %>
<%= link_to "new track", new_album_track_url(@album), method: :get %>
<%= link_to "edit", edit_album_url, method: :get %>
<%= link_to "delete", album_url, method: :delete %>

app/views/bands/_form.html.erb
<% submit_text = (band.persisted? ? 'Update' : 'Create') + ' band!' %>
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>
<h1><%= submit_text %> </h1>
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_input %>

  <label for="band_name">Name</label>
  <input type="text"
   name="band[name]"
   id='band_name'
   value="<%= @band.name %>"><br>

   <input type="submit" value="<%= submit_text %>">
</form>

app/views/bands/edit.html.erb
<%=
  render "form",
  band: @band
%>

app/views/bands/index.html.erb
<h1>All Bands</h1>
<ol>
  <% @bands.each do |band| %>
  <li>
    <%= link_to "#{band.name}", band_url(band) %>
  </li>
  <% end %>
</ol>
<div class="nav_bar">
  <%= link_to "new band", new_band_url , method: :get %>
</div>

app/views/bands/new.html.erb
<%=
render "form",
band: @band
%>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<p>Some would argue this is the best band ever</p>
<h2>Discography</h2>
<ol>
  <% @band.albums.each do |album| %>
  <li>
    <%= link_to "#{album.name}", album_url(album) %>
  </li>
  <% end %>
</ol>
<div class="nav_bar">
  <%= link_to "home", bands_url %>
  <%= link_to "new album", new_band_album_url(@band) , method: :get %>
  <%= link_to "edit", edit_band_url, method: :get %>
  <%= link_to "delete", band_url, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<%= render "shared/notices" %>
<%= render "shared/errors" %>
<%= yield %>
<%= render "shared/footer" %>
</body>
</html>

app/views/shared/_errors.html.erb
<% flash[:error] %>
<% flash[:errors] && flash[:errors].each do |msg| %>
<p><%= msg %></p>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class=log_out>
    <% if logged_in? %>
      <%= button_to "Log Out #{current_user.email}", session_url, method: :delete %>
    <% end %>
  </div>
</footer>

app/views/shared/_form.html.erb
<h1><%= title %></h1>
<form action="<%= action %>" method="post">
  <%= auth_input %>
  <label for="user_email">User Email</label>
  <input type="text"
    name="user[email]"
    value="<%= user.email %>"
    id="user_email"><br>

  <label for="password">Password</label>
  <input type="password"
    name="user[password]"
    value="<%= user.password %>"
    id="password"><br>

  <input type="submit" value="<%= title %>">
</form>

app/views/shared/_notices.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/tracks/new.html.erb
<h1>Add a track</h1>

<form action="<%= tracks_url %>" method="post">
  <%= auth_input %>
  <label for="track_name">Name</label>
  <input type="text"
   name="track[name]"
   id='track_name'
   value="<%= @track.name %>"><br>

  <label for="track_album_id">Album</label>
  <select name="track[album_id]" id="album_band_id">
    <% @album.band.albums.each do |album| %>
      <option
        <%= params[:album_id].to_i == album.id ? "selected" : ""%>
        value="<%= album.id %>">
        <%= album.name %>
      </option>
    <% end %>
  </select><br>

  <% Track::TRACK_TYPES.each do |track_type| %>
  <label for="track_type_<%= track_type %>">
    <%= "#{ track_type }" %>
  </label>
  <input type="radio"
    name="track[track_type]"
    id="album_type_<%= track_type %>"
    value="<%= track_type %>"
    <%= 'checked="checked"' if @track.track_type == track_type %>>
  <% end %><br>

  <input type="submit" value="submit">
</form>

app/views/users/new.html.erb
<%=
  render "shared/form",
  user: @user,
  title: "Sign Up",
  action: "#{users_url}"
%>

app/views/users/show.html.erb
<h1><%= current_user.email %></h1>
<p>good day to you sir</p>